name: Build and publish to PyPI

on:
  release:
    types: [published]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]  # Add more platforms if needed: ubuntu-latest, macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python (for cibuildwheel host)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # This is not the target version (3.10), just the version cibuildwheel runs on

      - name: Install dependencies
        run: python -m pip install --upgrade pip cibuildwheel build twine

      - name: Backup original setup.py
        run: python -c "import shutil; shutil.copyfile('setup.py', 'setup_original.py')"

      - name: Build compiled wheels with MyPyC
        env:
          CIBW_BEFORE_ALL: python -c "import shutil; shutil.copyfile('setup_mypyc.py', 'setup.py')"
#          CIBW_SKIP: "pp*"  # Explicitly skip PyPy builds
        run: cibuildwheel --output-dir wheelhouse

      - name: Restore original setup.py
        run: python -c "import shutil; shutil.copyfile('setup_original.py', 'setup.py')"

      - name: Build sdist (PEP 625 compliant)
        run: python -m build --sdist --outdir wheelhouse

      - name: Build pure Python wheel
        run: python -m build --wheel --outdir wheelhouse

      - name: Upload to Test PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
#          TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
#          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
        run: twine upload --verbose --skip-existing wheelhouse/* # FOR TESTING: --repository-url https://test.pypi.org/legacy/

      - name: Upload wheels to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: wheelhouse/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
